# spring:
# datasource:
# url: jdbc:mysql://localhost:3307/rent_car?createDatabaseIfNotExist=true
# username: root
# password: 1234
# driver-class-name: com.mysql.cj.jdbc.Driver
# jpa: 
#  hibernate: 
#    naming: 
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3307/studentManagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true



